name: CloudConnect
favicon: null
layout_spectrum: 0.7163678789511323
typography_spectrum: 0.13318761577829719
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.4092430283781141
  lightness: 0.6468755039386451
  saturation: 0.1037662960588932
  rhythmicContrast: 0.9665419743396342
purpose: []
